photoshelter.settings:
  type: config_object
  label: 'PhotoShelter API Config Settings'
  mapping:
    email:
      type: string
      label: 'Example Email'
    password:
      type: password
      label: 'Example Password'
    api_key:
      type: string
      label: 'Example API Key'
    last_full_sync:
      type: string
      label: 'Last Full Sync'
    last_sync:
      type: string
      labe: 'Last Sync'