photoshelter.settings:
  type: config_object
  label: 'PhotoShelter API Config Settings'
  mapping:
    email:
      type: string
      label: 'Example Email'
    password:
      type: password
      label: 'Example Password'
    api_key:
      type: string
      label: 'Example API Key'
    last_sync:
      type: string
      label: 'Last Sync'
    max_width:
      type: string
      label: 'Max Width'
    max_height:
      type: string
      label: 'Max Height'
    allow_private:
      type: boolean
      label: 'Allow Private'
    cron_sync:
      type: boolean
      label: 'Cron Sync'
    containers_names:
      type: sequence
      label: 'Container Names'
      sequence:
        type: mapping
        mapping:
          name:
            type: string
            label: 'Name'
          id:
            type: string
            label: 'ID'
          type:
            type: string
            label: 'Type'
